SOURCE_DIRS:
  - src/**/**/
  - vendor/Libraries/XMCLib/src/**/**/
  - vendor/Libraries/Newlib/**/
ARM_GCC: <ARM_BASE>arm-none-eabi-gcc
ARM_OBJCOPY: <ARM_BASE>arm-none-eabi-objcopy
ARM_SIZE: <ARM_BASE>arm-none-eabi-size
ARM_ASM_COMPILE_OPTIONS:
  - -x assembler-with-cpp
  - -c
  - -DXMC4700_F144x2048
  - -Wall
  - -mfloat-abi=softfp
  - -fmessage-length=0
  - -mcpu=cortex-m4
  - -mfpu=fpv4-sp-d16
  - -mthumb
  - -g
  - -gdwarf-2
ARM_COMPILE_OPTIONS:
  - -c
  - -DXMC4700_F144x2048 
  - -O0 
  - -ffunction-sections 
  - -fdata-sections 
  - -Wall 
  - -std=gnu99 
  - -mfloat-abi=softfp 
  - -pipe 
  - -fmessage-length=0 
  - -mcpu=cortex-m4 
  - -mfpu=fpv4-sp-d16 
  - -mthumb 
  - -g 
  - -gdwarf-2 
ARM_LINK_OPTIONS:
  - -nostartfiles 
  - -Xlinker 
  - --gc-sections 
  - -specs=nano.specs 
  - -specs=nosys.specs 
  - -mfloat-abi=softfp 
  - -mfpu=fpv4-sp-d16 
  - -mcpu=cortex-m4 
  - -mthumb 
  - -g 
  - -gdwarf-2 
LINKED_LIBRARIES:
  - -lm
# At the command line they end up like:
# "-I"compile-include-path" -I"PATH_TO_ARM_BASE/arm-none-eabi/include"
FURTHER_COMPILE_INCLUDES:
  - <ARM_BASE>arm-none-eabi/include
  - vendor/Libraries/XMCLib/inc
  - vendor/Libraries/CMSIS/Include
  - vendor/Libraries/CMSIS/Infineon/XMC4700_series/Include
STARTUP_SRC: Startup/
LINKER_FILE: linker_script.ld
GLOBAL_EXCLUDE: []
