# The //*.c means all c sources arbitrarily deep directories
# All directories of the source and the header files
# will be includeded with the "-I src/some/path" at the end in the commandline

sourceFiles:
  - src//*.c
  - vendor/Libraries/XMCLib/src//*.c
  - vendor/Libraries/Newlib//*.c
  - Startup//*.c
  - Startup//*.S
headerFiles:
  - src//*.h

# For compilation, ccBase and the others are joined with
# ccBase </> cc, resulting in
# f.e "/home/joe/bin/gcc-arm-none-eabi-4_9-2014q4/bin/arm-none-eabi-gcc
# please use absolute paths for ccBase
# The replacement rule is not generally supported by YAML,
# and works only for the 'ccBase' parameter

ccBase: /home/jakov/bin/gcc-arm-none-eabi-4_9-2014q4/bin
cc: <ccBase>arm-none-eabi-gcc # <ccBase> gets replaced and correctly concatenated
ccObjCopy: <ccBase>arm-none-eabi-objcopy
ccSize: <ccBase>arm-none-eabi-size

ccAsmOptions:
  - -x assembler-with-cpp
  - -c
  - -DXMC4700_F144x2048
  - -Wall
  - -mfloat-abi=softfp
  - -fmessage-length=0
  - -mcpu=cortex-m4
  - -mfpu=fpv4-sp-d16
  - -mthumb
  - -g
  - -gdwarf-2

ccCompileOptions:
  - -c
  - -DXMC4700_F144x2048 
  - -O0 
  - -ffunction-sections 
  - -fdata-sections 
  - -Wall 
  - -std=gnu99 
  - -mfloat-abi=softfp 
  - -pipe 
  - -fmessage-length=0 
  - -mcpu=cortex-m4 
  - -mfpu=fpv4-sp-d16 
  - -mthumb 
  - -g 
  - -gdwarf-2 

ccLinkOptions:
  - -nostartfiles 
  - -Xlinker 
  - --gc-sections 
  - -specs=nano.specs 
  - -specs=nosys.specs 
  - -mfloat-abi=softfp 
  - -mfpu=fpv4-sp-d16 
  - -mcpu=cortex-m4 
  - -mthumb 
  - -g 
  - -gdwarf-2 

ccLinkLibs:  
  - -lm
  
# At the command line they end up like:
# "-I"compile-include-path" -I"PATH_TO_ARM_BASE/arm-none-eabi/include"
compileIncludes:
  - <ccBase>arm-none-eabi/include
  - vendor/Libraries/XMCLib/inc
  - vendor/Libraries/CMSIS/Include
  - vendor/Libraries/CMSIS/Infineon/XMC4700_series/Include
  
# Leave empty if you don't have any
linkerFile: linker_script.ld

