/*********************************************************************************************************************
 * DAVE APP Name : I2C_MASTER       APP Version: 4.1.18
 *
 * NOTE:
 * This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
 *********************************************************************************************************************/

/**
 * @cond
 ***********************************************************************************************************************
 *
 * Copyright (c) 2015-2016, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG (dave@infineon.com).
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 *
 * 2015-02-16:
 *     - Initial version<br>
 *
 * 2015-04-06:
 *     - Optimized generation of config code<br>
 *
 * 2015-07-29:
 *     - Added DMA, direct mode support<br>
 * @endcond
 *
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#include "i2c_master.h"	
#if (UC_FAMILY == XMC1)
#include "xmc_scu.h"
#endif
/**********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/
/*
 * Function implements the data transmission. It is called from the transmit interrupt service handler.
 * Function pushes data to the output block and releases control. It is called again when the previous data is
 * transmitted. When transmit FIFO is used, the function sets the trigger limit based on the size of data to be
 * transmitted. This makes sure that the CPU usage is optimum.
 *
 * I2C_MASTER_t * pointer to the I2C_MASTER APP instance handle
 *
 */
void I2C_MASTER_TransmitHandler(I2C_MASTER_t * const handle);

void rx_callback_0(void);
void tx_callback_0(void);

volatile uint8_t tx_completion_0 = 0;
volatile uint8_t rx_completion_0 = 0;

/*
 * Function implements the data reception. It is called from the receive interrupt service handler.
 * Function reads data from the receive block and updates the user's buffer. It is called again when the data is
 * received again. When receive FIFO is used, the function sets the trigger limit based on the size of data to be
 * received. This makes sure that the CPU usage is optimum.
 *
 * I2C_MASTER_t * pointer to the I2C_MASTER APP instance handle
 *
 */
void I2C_MASTER_ReceiveHandler(I2C_MASTER_t * const handle);

void I2C_MASTER_0_init(void);
#if (I2C_MASTER_DMA_TX_ENABLED == 1)
void I2C_MASTER_0_dma_tx_handler(XMC_DMA_CH_EVENT_t event);
#endif
#if (I2C_MASTER_DMA_RX_ENABLED == 1)
void I2C_MASTER_0_dma_rx_handler(XMC_DMA_CH_EVENT_t event);
#endif

const XMC_I2C_CH_CONFIG_t I2C_MASTER_0_channel_config=
{
	.baudrate = (uint32_t)(400000U),
	.address  = 0
};

const I2C_MASTER_CONFIG_t I2C_MASTER_0_config =
{
	.brg_config = &I2C_MASTER_0_channel_config,
	.fptr_i2c_config = I2C_MASTER_0_init,
	.tx_cbhandler = tx_callback_0,
	.rx_cbhandler = rx_callback_0,
	.nack_cbhandler = NULL,
	.arbitration_cbhandler = NULL,
	.error_cbhandler = NULL,
	.transmit_mode = I2C_MASTER_TRANSFER_MODE_INTERRUPT,
	.receive_mode = I2C_MASTER_TRANSFER_MODE_INTERRUPT,
	.txFIFO_size = XMC_USIC_CH_FIFO_SIZE_16WORDS,
	.rxFIFO_size = XMC_USIC_CH_FIFO_SIZE_16WORDS

};
I2C_MASTER_RUNTIME_t I2C_MASTER_0_runtime =
{
	.tx_ack_sr = 0x1U,
	.tx_busy = false,
	.rx_sr = 0x0U,
	.rx_busy = false,
	.bus_acquired = false
};

I2C_MASTER_t I2C_MASTER_0 =
{
	.channel = XMC_I2C2_CH0,
	.config = &I2C_MASTER_0_config,
	.runtime = &I2C_MASTER_0_runtime
};

void I2C_MASTER_0_init(void)
{
	/* _ALT(n) configurations are dependend on the pinout you use:
	 * look at page 2557 (mikro-keil manual xmc4000)
	 */
	const XMC_GPIO_CONFIG_t I2C_MASTER_0_sda_pin_config   =
		{
			.mode = XMC_GPIO_MODE_OUTPUT_OPEN_DRAIN_ALT1,
			.output_level   = XMC_GPIO_OUTPUT_LEVEL_HIGH,
		};
	const XMC_GPIO_CONFIG_t I2C_MASTER_0_scl_pin_config   =
		{
			.mode = XMC_GPIO_MODE_OUTPUT_OPEN_DRAIN_ALT1,
			.output_level  = XMC_GPIO_OUTPUT_LEVEL_HIGH,
		};
	XMC_I2C_CH_Init(I2C_MASTER_0.channel, &I2C_MASTER_0_channel_config);

	XMC_USIC_CH_SetInputSource(I2C_MASTER_0.channel, XMC_USIC_CH_INPUT_DX1, 0); 
	XMC_USIC_CH_SetInputSource(I2C_MASTER_0.channel, XMC_USIC_CH_INPUT_DX0, 0); /*  Data Input select P5.1   */

	/* configure i2c tx fifo */
	XMC_USIC_CH_TXFIFO_Configure(I2C_MASTER_0.channel,
				     16,
					 I2C_MASTER_0_config.txFIFO_size,
				     (uint32_t)1);
	
	XMC_USIC_CH_TXFIFO_SetInterruptNodePointer(I2C_MASTER_0.channel,
						   XMC_USIC_CH_TXFIFO_INTERRUPT_NODE_POINTER_STANDARD,
						   ((uint32_t)4));

	/* Service request line 0 connects to interrupt number 96 */
	/* Service request line 5 connects to interrupt number 101 */
	XMC_USIC_CH_TXFIFO_EnableEvent(I2C_MASTER_0.channel, XMC_USIC_CH_TXFIFO_EVENT_CONF_STANDARD);

	/* configure i2c rx fifo */
	XMC_USIC_CH_RXFIFO_Configure(I2C_MASTER_0.channel,
				     0,
					 I2C_MASTER_0_config.rxFIFO_size,
				     (uint32_t)(15));

	XMC_GPIO_Init((XMC_GPIO_PORT_t *)PORT5_BASE, (uint8_t)1, &I2C_MASTER_0_sda_pin_config);
	XMC_GPIO_Init((XMC_GPIO_PORT_t *)PORT5_BASE, (uint8_t)2, &I2C_MASTER_0_scl_pin_config);
	
	/* 
	 * mikro-keil manual Page 170 for service request lines, 
	 * 
	 * uses (the obvious) direct mapping to interrupt vectors.
	 */
	/* Service request line 0 connects to interrupt number 96 */
	/* Service request line 5 connects to interrupt number 101 */
	XMC_USIC_CH_RXFIFO_SetInterruptNodePointer(I2C_MASTER_0.channel,
						   XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_STANDARD,
						   ((uint32_t)5));
	XMC_USIC_CH_RXFIFO_SetInterruptNodePointer(I2C_MASTER_0.channel,
						   XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_ALTERNATE,
						   ((uint32_t)5));
	
	XMC_USIC_CH_RXFIFO_EnableEvent(I2C_MASTER_0.channel, (XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE |
			XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD));

	/* is this necessairy ? */
//	XMC_USIC_CH_SetInterruptNodePointer(I2C_MASTER_0.channel,
//					    XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL,
//					    ((uint32_t)2));
	
	XMC_I2C_CH_Start(I2C_MASTER_0.channel);

	/* Tx interrupt priority settings */
	NVIC_SetPriority((IRQn_Type)101, NVIC_EncodePriority(NVIC_GetPriorityGrouping(),63,0));
	NVIC_EnableIRQ((IRQn_Type)101);

	/* Rx interrupt priority settings */
	NVIC_SetPriority((IRQn_Type)100, NVIC_EncodePriority(NVIC_GetPriorityGrouping(),63,0));
	NVIC_EnableIRQ((IRQn_Type)100);
}

/*Transmit ISR*/
void I2C_MASTER_0_TX_HANDLER()
{
	I2C_MASTER_TransmitHandler(&I2C_MASTER_0);
}
/*Receive ISR*/
void I2C_MASTER_0_RX_HANDLER()
{
	I2C_MASTER_ReceiveHandler(&I2C_MASTER_0);
}

/* Transmit callback handling */
void tx_callback_0(void)
{
	tx_completion_0 = 1;
}

/* Receive callback handling */
void rx_callback_0(void)
{
	rx_completion_0 = 1;
}


